### ISSUE TITLE
"client name already exists" after deleting application

### ISSUE THREAD

**Issue by myndzi** [twitchdev/issues#148] opened 2020-06-21 08:31 UTC
**Brief description**
I accidentally created an Extension instead of an Application. I deleted it, but subsequently I couldn't use that name anymore.

**How to reproduce**
Create an extension. Delete it, then try to create an Application with the same name.

**Expected behavior**
After deleting the created name, it should be usable again

**Screenshots**

**Additional context or questions**
I can see how this could be a security feature to some extent: you wouldn't want people to be able to imitate well-known extensions or applications. However, if the previous name was owned by me, this shouldn't be a problem -- or if it only existed for a couple of minutes.

**Comment by BarryCarlyon** [comment] 2020-06-21 11:25
> Expected behavior
> After deleting the created name, it should be usable again

Old names are held onto for a unknown time period, they are not released instantly. So time is given for various caches to clear. The name is often released more quickly when you rename the old applications rather than delete it.*

* citation not provided

It's not a bug, it's just not documented how long it takes to release the name

**Comment by lleadbet** [comment] 2020-07-28 19:38
Closing this issue since Barry is correct-there is an expected amount of time before the cache clears on the name. It should eventually free up.

**Closed by lleadbet** 2020-07-28 19:38 UTC
Labels: product: dev site
