### ISSUE TITLE
Image sizes wrong in non English Translations

### ISSUE THREAD

**Issue by BarryCarlyon** [twitchdev/issues#160] opened 2020-07-08 11:57 UTC
**Brief description**

For images that need to be 300x200
The translation says 300x300 leading to developer confusion when the uploaded image is rejected

**How to reproduce**

Use the developer console in not English

**Screenshots**

![image](https://user-images.githubusercontent.com/20999/86915806-8309f600-c11a-11ea-9329-a3d9f050b024.png)

**Additional context or questions**

https://discuss.dev.twitch.tv/t/cant-upload-image-300x300/26994

It was previously brought up on Discord before GitHub issues were a thing

**Comment by lleadbet** [comment] 2020-07-14 00:57
Duplicate of #119.

**Closed by lleadbet** 2020-07-14 00:57 UTC
Labels: product: dev site
