### ISSUE TITLE
Trailing spaces in display_name field

### ISSUE THREAD

**Issue by RAnders00** [twitchdev/issues#151] opened 2020-06-27 09:08 UTC
**Brief description**
Querying some users, the returned `display_name` has a trailing space, which I suspect is a bug.

**How to reproduce**
`GET https://api.twitch.tv/helix/users?login=itsvinc`

```json
{
  "data": [
    {
      "id": "41174867",
      "login": "itsvinc",
      "display_name": "ItsVinc ",
      "type": "",
      "broadcaster_type": "",
      "description": "",
      "profile_image_url": "https://static-cdn.jtvnw.net/jtv_user_pictures/12fa7203-4acd-40db-8970-84fd1cc781a7-profile_image-300x300.png",
      "offline_image_url": "",
      "view_count": 374
    }
  ]
}
```

Notice the `display_name` field, and the value `ItsVinc `.

**Expected behavior**
`display_name` is properly sanitized.

**Screenshots**

**Additional context or questions**
The same messed up display name pops up in other Twitch API products too, e.g. `display-name` tag in IRC, on the V5 API, etc.

Linked issue: https://github.com/robotty/dank-twitch-irc/issues/33

**Comment by BarryCarlyon** [comment] 2020-06-28 18:02
It's not a bug.

Some users have had a space on their display name for ages for various reasons and manifests as a `\s` on IRC

Usually indicates a name change back when they were done manually.

The users display name _literally_ has a space on the end.

**Comment by RAnders00** [comment] 2020-06-28 19:18
Couldn't this be fixed for all users and then all is well? (Remove the space for the affected users)

I think "not a bug" is not a useful attitude here. Nowhere does it say that usernames are intended to have spaces at the end, neither does it say anywhere that trimming them is advisable. This is just one more oddity that literally everybody will have to work around in their implementations.

**Comment by BarryCarlyon** [comment] 2020-06-29 02:26
> Nowhere does it say that usernames are intended to have spaces at the end,

Because this isn't the username it's the display name, totally different to the user or login name.

The display name can differ WILDLY compared to the user/login name

The display name is _often_ the captilisation of a username as set by the user but can also be the localised name (for Korean names). So whilst yes a space at the end of the display name is odd, it is not invalid.

**Comment by jbulava** [comment] 2020-07-21 20:34
The trailing spaces issue has been reviewed by the appropriate product teams.  This is a data hygiene issue for older accounts when this information was entered manually.  Proper display names (that do not contain Chinese, Japanese, or Korean characters) cannot contain these spaces.

While we had not previously considered going back and trimming trailing spaces, the team has created a ticket to consider this action. Since this is technically not a bug I will close the issue, but wanted to communicate the eventual intent to clean up spaces.

**Closed by jbulava** 2020-07-21 20:34 UTC
Labels: product: helix
