### ISSUE TITLE
/chat/emoticon_images returns 500 Internal Server Error

### ISSUE THREAD

**Issue by RAnders00** [twitchdev/issues#107] opened 2020-05-09 07:55 UTC
**Brief description**
When calling the emoticon_images endpoint:

```
curl -v https://api.twitch.tv/kraken/chat/emoticon_images?emotesets=0&client_id=472wm7d2oxkundpqsy1abmjjxqnuiq&api_version=5
```

I receive as the response:

```json
{"error":"Internal Server Error","status":500,"message":""}
```
As well as status code 500.

**How to reproduce**

See command above

**Expected behavior**

**Screenshots**

**Additional context or questions**

**Comment by BarryCarlyon** [comment] 2020-05-11 17:28
Duplicate of

https://github.com/twitchdev/issues/issues/50

**Closed** 2020-05-11 17:52 UTC
Labels: product: v5
