### ISSUE TITLE
Bits in extensions: starting or ending with Zero Balance: results in an error/failiure/bits used no receipt state

### ISSUE THREAD

**Issue by BarryCarlyon** [twitchdev/issues#509] opened 2021-10-05 18:40 UTC
**Brief description**

If a user has a zero balance of bits.
tries to use bits in an extension.
An error dialog is raised instead of the "you need to buy bits from Twitch" dialog

The state (release/test) is irrelevant here)

**How to reproduce**

- Have zero bits in your wallet
- try to use bits in any extension

**Expected behavior**

The "you need to get some bits" dialog appear similar to

![image](https://user-images.githubusercontent.com/20999/136083310-8c3023b7-943b-4b6e-a23c-db02e58bd0a6.png)

**Screenshots**

Released:
![image](https://user-images.githubusercontent.com/20999/136083100-0e8963e3-6643-44ab-b236-b8525793f9d0.png)

![image](https://user-images.githubusercontent.com/20999/136083848-1b99972c-8fc1-4238-a5ed-45a183e76e13.png)

Test example:
![image](https://user-images.githubusercontent.com/20999/136083339-7d0c1e70-7b45-4008-aec8-c7e975ed2442.png)

**Additional context or questions**

**Comment by BarryCarlyon** [comment] 2021-10-05 19:29
Problem doesn't occur on mobile:

![image](https://user-images.githubusercontent.com/20999/136090070-63b877d2-906d-4247-90b7-e953f619549b.png)

**Comment by streamstickers** [comment] 2021-12-22 17:28
Bump. There is a good chance this same bug may be related to a much more serious bug that causes transaction failures for zero bit users.

Around the same time this bug was logged, we started getting reports of users not consistently receiving stickers after Twitch debited their account. In these cases, the frontend would hang, and we would have no record of the transaction in our system. 

After many months of digging, we finally found a way to reproduce the issue and it only seems to happen if the user in question makes a transaction that leaves zero bits in their bank. If that happens, the extension FE locks up and while Twitch debits the bits, we get no transaction complete callback and no record in our system of it ever happening.

We believe there could be a good chance these two items may be related as I was able to repro this issue about 10 times in a single day, all with the user in question being left with a zero bank after Twitch took the bits.

**Steps I used to reproduce:**

Load a streamer running the extension with 0 bits
Purchase 100 bits
Use the extension to purchase a 100 bits sticker (without refreshing the page)
Twitch will debit the user, the FE will fail as no OnComplete callback is triggered.

**Expected Result:**

All transactions should trigger the same responses from Twitch regardless of the users final bank balance.

**Comment by streamstickers** [comment] 2021-12-24 05:11
More user reports of this issue from 12/23. It’s the same scenario where the user had zero bits in their bank at the time of failure:

![88EACD94-A475-4BED-9714-B93DCF4550A7](https://user-images.githubusercontent.com/64783296/147318976-68eef95f-1dc5-4e60-828b-20312a20e7c0.jpeg)

**Comment by SylvainSimon** [comment] 2021-12-24 11:00
Apparently twitch doesn't give much importance to a major problem in its bit payment system. It's sad.
3 months reporting...

**Comment by ZachBora** [comment] 2022-01-06 02:15
Would love this to be fixed!
Has happened to me more than once while spending bits on extensions.

**Comment by jbulava** [comment] 2022-01-11 21:36
We wanted to provide update regarding this issue. The team is actively investigating and there should be a followup to share in the next week.  They have confirmed, as stated above, that the issue does not occur on mobile and therefore have a good idea of where the problem is occurring.  Thanks for your patience.

**Comment by jbulava** [comment] 2022-01-13 00:37
A fix for this issue has been committed and should be included in a deployment tomorrow (January 13).

**Closed** 2022-01-13 22:51 UTC
Labels: urgent, product: extensions, ticketed
