### ISSUE TITLE
Nested JSON in Pubsub channel sub endpoint

### ISSUE THREAD

**Issue by TzuHsuan** [twitchdev/issues#377] opened 2021-04-26 14:16 UTC
**Brief description**
data.message value comes as JSON, thus will have to be parsed twice

**How to reproduce**
All Subscription messages received from the endpoint have this issue, not sure about other endpoints.

**Expected behavior**
Non-nested JSON

**Screenshots**

**Additional context or questions**

**Comment by iProdigy** [comment] 2021-04-26 17:40
The standard format of pubsub has `data.message` as a string, so this is not a regression for the subscriptions topic. The docs have a small note for the topic that `message is a JSON object that has been escaped (see “Example: Bits Event Message”) and cast into a string` so it's easy to not realize that the example messages in the docs for this topic (which avoid the casting for readability) are not quite what you'd receive over the websocket

**Comment by lleadbet** [comment] 2021-10-04 14:18
Given the above, closing as it's not a bug, just a bit confusing.

**Closed by lleadbet** 2021-10-04 14:18 UTC
Labels: product: pubsub
