### ISSUE TITLE
Can't create unique game tag

### ISSUE THREAD

**Issue by Gaming2101** [twitchdev/issues#1025] opened 2024-11-28 11:57 UTC
**Brief description**
I am unable to find the process for creating a unique game tag for my game ARENA for twitch. I cannot find any information on this either. I don't know if this is a bug or mistake, but this is an issue for me.

**Expected documentation**
I am expecting to find something on creating a unique tag for my game, but I cannot find any information regarding this.

**Screenshots**
<img width="1184" alt="Screenshot 2024-11-28 195512" src="https://github.com/user-attachments/assets/111a9922-3f23-4de7-a84b-e5ed6c0cb3c8">

**Additional context or questions**
Is there a special process for this, because I am having great trouble finding it.
Could I please have some assistance.

Thanks.

**Comment by thedist** [comment] 2024-11-28 12:15
Duplicate of #1026

**Closed** 2024-11-28 18:14 UTC
Labels: product: docs
