### ISSUE TITLE
Broadcaster Subscriptions Missing Date

### ISSUE THREAD

**Issue by Siriuo** [twitchdev/issues#564] opened 2022-02-01 23:21 UTC
**Brief description**
Broadcaster Subscriptions is missing the date of creation or sub date. v5 has this but helix doesn't.,

**Expected behaviour**
Broadcaster subscriptions to return sub or creation date

**Comment by BarryCarlyon** [comment] 2022-02-02 16:53
This is not a bug.

https://dev.twitch.tv/docs/api/reference#get-broadcaster-subscriptions

It's not documented as being there.

This is a feature request

Similar/related uservoice 

https://twitch.uservoice.com/forums/310213-developers/suggestions/37659133-subs-tenure-in-helix

**Comment by Siriuo** [comment] 2022-02-02 18:47
Ah thanks for the info. Couldn't post in the uservoice yesterday for some reason. I can today. https://twitch.uservoice.com/forums/310213-developers/suggestions/44750122-subscriber-start-date is the link to the post.

**Comment by marcandrews** [comment] 2022-03-18 15:59
Since Helix is supposed to replace Kraken, and Kraken had this information, this is considered acceptance criteria that was never delivered, ergo a bug.

**Comment by BarryCarlyon** [comment] 2022-03-18 16:04
@marcandrews your problem is solved via EventSub which will send the most recent sub/resub in real time/filter accordingly

Kraken was super inaccuate with the dates/those dates were not _useful_ for calculate tenure of true most recent. So for your use case from 290 it's wasn't in kraken anyway in my opinion.

Missing functionality in Helix compared to Kraken is not a bug to be reported to the Bug Tracker.
It's a feature request needed to be filed on UserVoice along with the use case.
This is the preferred method to report this sort of issue.

ergo not a bug to be reported to this bug tracker.

**Comment by BarryCarlyon** [comment] 2022-03-18 16:19
I'm assuming you are already authenticated in order to collect subscriber data from PubSub or Helix in the first place. (and not using an anonomous chat bot) and as an extension you can create eventsub's the moment they activate the extension and you get an auth (or even use the auth.create eventsub to then create eventsubs so you don't need a ping back from the config view/some other way)

So yeah at "sign up" you wouldn't have the recent sub but it would populate when subs occur. And the list of recents held on the server/not loaded at overlay load.

**Comment by marcandrews** [comment] 2022-03-18 16:22
Yeah, that's an unhealthy amount assumptions 😅

**Comment by Xemdo** [comment] 2023-08-15 22:09
As noted previously, this has been filed as a feature request and is not considered a bug: https://twitch.uservoice.com/forums/310213-developers/suggestions/44750122-subscriber-start-date

Will close this out for now.

**Closed by Xemdo** 2023-08-15 22:09 UTC
Labels: product: api
