### ISSUE TITLE
Application Registration Failure

### ISSUE THREAD

**Issue by Sam-Aster** [twitchdev/issues#846] opened 2023-10-07 03:16 UTC
**Brief description**
"Create" button refreshes reCAPTCHA but does not proceed with registration
**How to reproduce**
I went to https://dev.twitch.tv/console/apps/create, filled out the proper details and went through reCAPTCHA verification, and clicked "Create", just to see nothing happen but the reCAPTCHA refresh and expect verification again.
**Expected behavior**
Continue through the process of application registration or testing.
**Screenshots**
https://drive.google.com/file/d/1E2Z-L7sKkQ_Y_XiaOdXhiSKSLb_gJWOP/view?usp=sharing
**Additional context or questions**

**Comment by Dkamps18** [comment] 2023-10-07 04:04
Application name has to be unique. "Cosmos" might already be taken try with something after it or something different.

**Comment by BarryCarlyon** [comment] 2023-10-07 11:38
Duplicate of #831

**Comment by Sam-Aster** [comment] 2023-10-07 20:37
> Duplicate of #831 

Courtesy of information of the same nature as @Dkamps18, I was able to figure out the resolution. I offer my apologies for not doing my due diligence before posting.

**Comment by Xemdo** [comment] 2023-10-13 18:08
Closing as this is a duplicate of 831.

**Closed by Xemdo** 2023-10-13 18:08 UTC
Labels: product: dev site
