### ISSUE TITLE
Cannot clone to/create version 1.0.0 / It made it anyway

### ISSUE THREAD

**Issue by BarryCarlyon** [twitchdev/issues#43] opened 2020-01-28 14:56 UTC
**Brief description**

Cannot clone to or create version "1.0.0"

**How to reproduce**

Clone from a version to 1.0.0, or create 1.0.0

**Expected behavior**

Creates 1.0.0

**Screenshots**

Create client side check

![image](https://user-images.githubusercontent.com/20999/73274813-1a6b3480-41de-11ea-8516-e0977c6c678e.png)

Create server side check

![image](https://user-images.githubusercontent.com/20999/73274839-2656f680-41de-11ea-9b73-c55ab358297b.png)

Clone Client Side check

![image](https://user-images.githubusercontent.com/20999/73274879-37076c80-41de-11ea-9a7b-5633e2467eb6.png)

Clone Server Side Check

![image](https://user-images.githubusercontent.com/20999/73274888-3cfd4d80-41de-11ea-8854-8c9ff0d945a9.png)

**Comment by BarryCarlyon** [comment] 2020-01-28 14:57
Same issue for version `0.1.0`

**Comment by BarryCarlyon** [comment] 2020-01-28 14:57
Same issue with `0.0.5`

**Comment by BarryCarlyon** [comment] 2020-01-28 15:00
The UI Errored but still created the version(s)

![image](https://user-images.githubusercontent.com/20999/73275320-d9275480-41de-11ea-89bb-1cb15e0e7c93.png)

**Comment by mauerbac** [comment] 2020-03-23 19:42
DXL-485

**Comment by mauerbac** [comment] 2020-03-25 16:19
Hey @BarryCarlyon - the team couldn't reproduce. Can you confirm this is still happening ?

**Comment by BarryCarlyon** [comment] 2020-03-25 19:59
It happens infrequently when the entire dashboard has a bad day

**Comment by jbulava** [comment] 2020-05-08 23:22
Unfortunately, the team cannot find an issue at this time so investigation has paused. Closing for now, but please let us know if there is a specific timeframe if this should pop back up.

**Closed by jbulava** 2020-05-08 23:22 UTC
Labels: product: dev site, stopped investigating, ticketed
