### ISSUE TITLE
`helixToken` `undefined` in mobile apps

### ISSUE THREAD

**Issue by freaktechnik** [twitchdev/issues#455] opened 2021-07-24 11:37 UTC
**Brief description**
Extensions now get a `helixToken` to make calls to the Twitch API from the front-end. However, this token is not passed in the Android app (yet).

**How to reproduce**
Output `helixToken` in the onAuthorized callback when the extension is loaded in the Android app.

**Expected behavior**
`helixToken` is documented without caveats of availability, so it should be available everywhere the extension is loaded.

**Screenshots**

**Additional context or questions**
The Twitch app on Android I'm using is Version 11.1.0 and Google Play offers me no update. I have also had matching reports from users of the extension.

**Comment by BarryCarlyon** [comment] 2021-07-26 13:11
I have confirmed that this bug is present on the Twitch iOS App as well

Twitch App Release: 11.1
TestFlight: Twitch App Beta: version 11.2

**Comment by BarryCarlyon** [comment] 2021-07-26 13:12
iOS test extension: 

![IMG_9079](https://user-images.githubusercontent.com/20999/126994448-ce2184ad-3496-4423-b3de-a69b129a4a05.PNG)

**Comment by lleadbet** [comment] 2021-07-26 14:28
👋 - We're aware of this and looking to get it included in an upcoming mobile release. I'll close this when that's gone out.

**Comment by Tandashi** [comment] 2021-09-22 09:46
👋 Any updates on this topic so far? Like when a release might come out / if any release is planned yet since it's been about 2 months now.

**Comment by ryanpf** [comment] 2021-12-30 16:42
Is there a recommended workaround for getting a user's display name while this bug exists?

**Comment by BarryCarlyon** [comment] 2021-12-30 16:43
> Is there a recommended workaround for getting a user's display name while this bug exists?

The same way we did before helixToken was introduced: use an EBS/backend service

**Comment by JosePascual** [comment] 2022-02-09 12:33
Any update?

**Comment by BarryCarlyon** [comment] 2022-04-13 18:06
Update:

seems it has a key in the object but the value is undefined

![IMG_9491](https://user-images.githubusercontent.com/20999/163242912-47b810c5-6e49-4702-a7ae-8e0e7d328cb2.PNG)

**Closed** 2023-08-22 17:56 UTC
Labels: product: extensions
