### ISSUE TITLE
No ReRuns in Helix

### ISSUE THREAD

**Issue by BarryCarlyon** [twitchdev/issues#38] opened 2020-01-18 11:08 UTC
**Brief description**

A while ago not long after Helix was introduced the filter and ability to even see ReRuns was removed from the helix streams endpoint

**Comment by BarryCarlyon** [comment] 2020-01-18 11:11
See also

https://discuss.dev.twitch.tv/t/new-twitch-api-deprecating-get-streams-by-type/14554

Where the deprecation was published.

**Comment by BarryCarlyon** [comment] 2020-02-12 12:59
This _also_ affects Webhooks :-|

**Comment by lleadbet** [comment] 2020-08-09 02:07
Tracking internally as HLX-1447. 

This would affect webhooks since we simply return the same data.

**Comment by Marstead** [comment] 2021-01-27 19:56
Would resolving this issue include reporting whether a stream is live, running a rerun, or showing offline separately? What's the current intended behavior? (My hope is that it is intended to report the three statuses separately, but the last time I used Reruns, they were indistinguishable from live streams on the API)

**Comment by Xemdo** [comment] 2023-08-09 00:38
This is more or less a feature request now. Reruns currently only add a stream tag, and there's an open User Voice for this to be added:
https://twitch.uservoice.com/forums/310213-developers/suggestions/39718135-show-reruns-in-helix-streams-as-type-rerun

**Closed by Xemdo** 2023-08-09 00:38 UTC
Labels: product: api, ticketed
