### ISSUE TITLE
User theme switch doesn't changes the context's theme field

### ISSUE THREAD

**Issue by anddorua** [twitchdev/issues#176] opened 2020-07-23 10:32 UTC
**Brief description**

When user switches the theme (light/dark) the context's **theme** filed still contains the previous value.

**How to reproduce**

Subscribe to the extension's helper onContext data and observe the value of the **theme** field while switching the theme on the user menu. 

**Expected behavior**

**theme** field of the context data should reflect the actual state of the "Dark Theme" switch.

**Screenshots**

![Screenshot from 2020-07-23 13-28-11](https://user-images.githubusercontent.com/5493450/88276999-a6bb6780-cce8-11ea-8761-7a72f56b1781.png)

**Additional context or questions**

N/A

**Comment by BarryCarlyon** [comment] 2020-07-23 11:48
Duplicate of #13

**Comment by lleadbet** [comment] 2020-09-09 02:06
Duplicate, but this issue is now resolved.

**Closed by lleadbet** 2020-09-09 02:06 UTC
Labels: product: extensions
