### ISSUE TITLE
Extension API endpoints in Twitch API reference?

### ISSUE THREAD

**Issue by BarryCarlyon** [twitchdev/issues#443] opened 2021-07-14 11:46 UTC
**Brief description**

As of yesterdays change log https://dev.twitch.tv/docs/change-log

There are a number of new Twitch API Extension endpoints.

All of these new endpoints are in the "Twitch API" reference
And the "Extensions" Reference refers to the "old" endpoints and doesn't mention the new endpoints

**Expected documentation**

Keep all the "Twitch API" Extensions Endpoints in the "Extensions" Reference

**Additional context or questions**

Extensions in Twitch API reference starts here https://dev.twitch.tv/docs/api/reference#get-extension-configuration-segment
Extensions in Extensions Reference is here https://dev.twitch.tv/docs/extensions/reference#endpoints

**Comment by jbulava** [comment] 2021-07-19 23:45
This is intended. The new Twitch API Extension endpoints were added in preparation of [today's announcement](https://discuss.dev.twitch.tv/t/how-extensions-are-affected-by-the-legacy-twitch-api-v5-shutdown/32708) as to how the v5 shutdown affects Extensions. The original Extensions reference now includes a banner to state they are deprecated.

With the new endpoints in the API reference, all endpoints can be found in one place.  I can understand the request to have the Extensions-specific endpoints in the Extensions section since it contextually makes sense, so we'll figure out the best way to solve both.  For now, I'll close this since it's not a bug.

**Closed by jbulava** 2021-07-19 23:45 UTC
Labels: product: docs
