### ISSUE TITLE
Streams and tags APIs are missing certain tags seen on twitch.tv

### ISSUE THREAD

**Issue by CBenni** [twitchdev/issues#371] opened 2021-04-19 15:35 UTC
**Brief description**
When looking at the data returned by the endpoints https://api.twitch.tv/helix/tags/streams and https://api.twitch.tv/helix/streams, I noticed a large number of tags seen on twitch (many of which seem to be connected to the game the streamer has set) are missing from the API entirely, showing up neither on the streams, nor the tags API.

**How to reproduce**
Load a streams object for a streamer that is live with a game (Dark Souls 2 works well), and compare the returned tags to those visible on twitch. In the example below, twitch shows 6 tags (English, No Backseating, RPC, Action, Open World, Adventure Game), while the API only has the first two.

**Expected behavior**
The API returns all tags seen on twitchs website.

**Screenshots**
![Lowko's stream tags](https://i.nuuls.com/uSLxM.png)
![Twitch API result](https://i.nuuls.com/iRzbL.png)

**Additional context or questions**
Some investigation by @BarryCarlyon showed that loading the full list of stream tags shows that requests to the list endpoint (with a limit=100) returns less than 100 items in most cases. This supports the suspicion that there is some missing data here.

**Comment by BarryCarlyon** [comment] 2021-04-19 15:36
Additional notes in #370 a duplicate of sorts

**Comment by Xemdo** [comment] 2023-08-16 23:01
Is this still relevant after the addition of freeform tags?

**Closed** 2023-08-22 18:42 UTC
Labels: product: api
