### ISSUE TITLE
Get Teams and Get Channel Teams - bad timestamps returned

### ISSUE THREAD

**Issue by chillymosh** [twitchdev/issues#644] opened 2022-09-01 16:23 UTC
**Brief description**
When using Get Channel Teams and Get Teams endpoint the created_at and updated_at fields are returning non RFC3339 format data, it looks like it is trying to return some form of epoch
```
{"data":
[{"broadcaster_id":"37402112",
"broadcaster_name":"shroud"
"broadcaster_login":"shroud",
"background_image_url":"https://static-cdn.jtvnw.net/jtv_user_pictures/team-loadedllc-background_image-f8819c7e467c49ae98d223542f03089d.png",
"banner":"https://static-cdn.jtvnw.net/jtv_user_pictures/team-loadedllc-banner_image-8f36bdc35de7429fad43abb4f7e780be-640x125.png",
"created_at":"seconds:1533233173  nanos:304884000",
"updated_at":"seconds:1619466719  nanos:586825000",
"info":"Heroic influencers for heroic brands.",
"thumbnail_url":"https://static-cdn.jtvnw.net/jtv_user_pictures/team-loadedllc-team_logo_image-10567f1fb93447e3acf3f645e295e591-600x600.jpeg",
"team_name":"loadedllc",
"team_display_name":"Loaded",
"id":"5467"}]}
```

**How to reproduce**
curl -X GET each endpoint 
```
https://api.twitch.tv/helix/teams/channel?broadcaster_id=37402112
https://api.twitch.tv/helix/teams?id=5467
```

**Expected behavior**
Return RFC3339  fromat
```
"created_at": "2019-02-11T12:09:22Z",
"updated_at": "2020-11-18T15:56:41Z",
```
**Screenshots**

**Additional context or questions**

**Comment by BarryCarlyon** [comment] 2022-09-01 16:25
Duplicte of the unclosed/unfuxed #347  I guess :-P

**Comment by Xemdo** [comment] 2023-08-21 23:14
Duplicate of #347 which has been since resolved

**Closed by Xemdo** 2023-08-21 23:14 UTC
Labels: product: api
