### ISSUE TITLE
"Get Ad Schedule" wrong timestamp format

### ISSUE THREAD

**Issue by YannickFricke** [twitchdev/issues#961] opened 2024-06-09 00:59 UTC
**Brief description**
https://dev.twitch.tv/docs/api/reference/#get-ad-schedule

It shows wrong information about the timestamps.

The production API returns timestamps in seconds / milliseconds (as integers) since unix epoch and not timestamps in RFC3339 format as described.

**Expected documentation**
The "snooze_refresh_at", "next_ad_at" and "last_ad_at" return timestamps in seconds / milliseconds (as integers) since unix epoch.

**Screenshots**
![grafik](https://github.com/twitchdev/issues/assets/591450/24c58b47-5192-482c-b626-9818f7345f1f)
![grafik](https://github.com/twitchdev/issues/assets/591450/c371b4b3-68d3-41dd-b1ca-b954ad614f42)

**Additional context or questions**

**Comment by YannickFricke** [comment] 2024-06-09 01:16
Related to this comment:

https://github.com/twitchdev/issues/issues/857#issuecomment-1800822567

**Comment by Xemdo** [comment] 2024-09-17 23:52
Duplicate of #857

**Closed by Xemdo** 2024-09-17 23:52 UTC
Labels: product: docs
