### ISSUE TITLE
Get Oauth error on Get Videos endpoint

### ISSUE THREAD

**Issue by MikePenhall** [twitchdev/issues#155] opened 2020-07-02 03:35 UTC
**Brief description**
According to the get videos docs, I shouldn't need authentication to use this endpoint, just my Client-ID. However when I try to access it I get an "OAuth token is missing" error. https://dev.twitch.tv/docs/api/reference#get-videos

**How to reproduce**
1. Make a curl request to https://api.twitch.tv/helix/videos?id-[videoid] as per the example on https://dev.twitch.tv/docs/api/reference#get-videos

eg. 
curl -H 'Client-ID: [my client id]' \
-X GET 'https://api.twitch.tv/helix/videos?id=[video id]'

2. Get a response:
{"error":"Unauthorized","status":401,"message":"OAuth token is missing"}

**Expected behavior**
Returns a video data object

**Screenshots**
![getvideotwitch](https://user-images.githubusercontent.com/2482983/86313587-9845d700-bc79-11ea-9045-c1b9941435fd.png)

**Additional context or questions**
Even passing in a valid oauth token in the header doesn't seem to return a valid response (get the same error as above). Am I doing something wrong?

**Comment by BarryCarlyon** [comment] 2020-07-02 14:52
![image](https://user-images.githubusercontent.com/20999/86373949-e5c34380-bc7b-11ea-8cb2-3ba4b6d768de.png)

This is a documentation bug that was introduced two Fridays ago.

ALL of helix requires an oAuth token.

https://discuss.dev.twitch.tv/t/requiring-oauth-for-helix-twitch-api-endpoints/23916

The error is correct, this is not a bug.

**Comment by jbulava** [comment] 2020-07-02 17:36
Barry is correct, this is an error in our documentation following the new helix endpoints that were released. The documentation team is aware.  For the time being, please follow the curl format in other examples with authentication.

**Comment by MikePenhall** [comment] 2020-07-02 19:18
OK thanks for the prompt reply guys.

**Comment by jbulava** [comment] 2020-08-20 18:01
We have the example fixes prepared for an update and they should be available soon.  Leaving the associated UserVoice entries open until that time, but closing this issue.

**Closed by jbulava** 2020-08-20 18:01 UTC
Labels: product: docs
