### ISSUE TITLE
Helix moderation/banned/events and moderation/banned return incomplete events/pagination issues

### ISSUE THREAD

**Issue by ChrisGuilbault** [twitchdev/issues#396] opened 2021-05-15 08:53 UTC
**Brief description**
moderation/banned/events only returns a  partial list of what moderation/banned returns and neither is a complete list. 
moderation/banned returns a pagination token but does not appear to advance the results causing results to just loop.
moderation/banned/events does not return a pagination token.

Also using user_id returns an empty struct on the moderation/banned/events.

**How to reproduce**
Make a helix request to either url below on a channel with more then 100 banned users.
"https://api.twitch.tv/helix/moderation/banned?first=100&broadcaster_id="
"https://api.twitch.tv/helix/moderation/banned/events?first=100&broadcaster_id="

**Expected behavior**
Both endpoints should return a complete list of banned users or banned user events with functioning pagination tokens.

**Screenshots**
None required.

**Additional context or questions**
This information was requested by a broadcaster that wishes more information about giving members a second chance then provided by the unban request function in mod view. The events end point is the only way to collect historical data from before I started working with the broadcaster.

**Comment by BarryCarlyon** [comment] 2021-05-17 17:45
See also #330 not a bug

Intended, the events API's only go back around 5 days or so.
It's missing from the documentation.

And see #18 regarding getting all banned users

**Comment by jbulava** [comment] 2021-05-17 18:18
Closing since Barry provided the other relevant issues to reference.

**Closed** 2021-05-17 18:17 UTC
Labels: product: api
