### ISSUE TITLE
Developer Console - Can't add new extension

### ISSUE THREAD

**Issue by RoccoNatuzzi** [twitchdev/issues#638] opened 2022-08-04 10:37 UTC
**Brief description**
It no longer seems to be possible to create a new extension in the Dev Console.

**How to reproduce**
1. Go to https://dev.twitch.tv/console/extensions/create
2. Try to create an application

**Expected behavior**
Create new extension

**Screenshots**
![image](https://user-images.githubusercontent.com/31292602/182826953-f564aecb-b406-4f6f-85b9-8bcc24517527.png)
![image](https://user-images.githubusercontent.com/31292602/182827186-143e80aa-0ce7-4c02-a74d-c65a3f222f08.png)

**Additional context or questions**
Try with all random name. Same problem from Developer Rig

**Comment by BarryCarlyon** [comment] 2022-08-04 21:23
Duplicate of #634

**Closed** 2023-09-05 18:22 UTC
Labels: product: dev site
