### ISSUE TITLE
Helix `Get Streams` missing online streams, can't migrate from v5

### ISSUE THREAD

**Issue by ABCRic** [twitchdev/issues#558] opened 2022-01-19 14:02 UTC
**Brief description**
The Helix `Get Streams` endpoint is missing streams that are online, after initially reporting them as online.

WIthin an initial window of about 30s-1min after stream start, requests intermittently show the stream as online as cache warms up - this is expected. However, any requests past around the minute mark behave as if the stream is not online and instead just return an empty `data` list.

My current use case uses Get Stream By Id from v5 which behaves correctly, but that's going away soon so and `Get Streams` in Helix is the migration path indicated in the guide.

**How to reproduce**
Tests were run using my channel at `twitch.tv/abcric`.
1. start streaming
2. wait 30 seconds
3. request https://api.twitch.tv/helix/streams?user_id=26735539 (with bearer token and client-id), returns correct result (1 stream)
4. wait another minute
5. request https://api.twitch.tv/helix/streams?user_id=26735539 (with bearer token and client-id), returns empty result (0 streams)

**Expected behavior**
Endpoint returns the stream data instead of an empty list.

**Screenshots**
Endpoint returning empty response even though stream has been online for more than 10 minutes and has viewers:
![image](https://user-images.githubusercontent.com/11618441/150139124-7584face-25a5-4e33-b5ba-e247ea6f05fa.png)

Endpoint results over time, 5 second interval (stream started at 13:45:09):
![image](https://user-images.githubusercontent.com/11618441/150143317-863ae3ac-f163-4474-ad33-68c73905d3eb.png)

Second example, same as above (stream started at 13:52:52):
![image](https://user-images.githubusercontent.com/11618441/150145299-76a7f6e3-4241-4da6-a2c5-0f93d5de3ff9.png)

**Additional context or questions**
I've posted about this issue in the dev forum at https://discuss.dev.twitch.tv/t/get-streams-endpoint-still-missing-online-streams/36265 which has some more context.

Get Streams from v5 shows the same broken behavior, although fixing that at this point is moot.
Get Stream By Id from v5 works correctly.

EventSub webhooks correctly report when the stream goes online and offline. Meaning, for the period between ~1 minute after stream start and until stream end, the backend as viewed via EventSub acknowledges the stream is online, but viewed via `Get Streams` it does not. However, as per the forum thread, EventSub is not sufficient for my use case.

**Comment by BarryCarlyon** [comment] 2022-01-19 15:43
Duplicate of #11

**Comment by ABCRic** [comment] 2022-02-15 15:50
Is this ever getting looked into? v5 is shutting down in 13 days, the Helix alternative is still broken.

**Comment by Xemdo** [comment] 2023-08-15 21:34
Closing as this is likely not still occurring. It seems the issue is related to one that was noticed in late 2022. That issue was related to a backend service issue and should have been fixed. If this can be reproduced again we'll look back into it, but it seems resolved for now.

**Closed by Xemdo** 2023-08-15 21:34 UTC
Labels: product: api
