### ISSUE TITLE
Bug with the creation of the application

### ISSUE THREAD

**Issue by 0Mrbilal0** [twitchdev/issues#866] opened 2023-11-18 21:43 UTC
**Brief description**

When I click on the button for create my application I have this error.

**How to reproduce**

**Expected behavior**

**Screenshots**
<img width="1267" alt="image" src="https://github.com/twitchdev/issues/assets/77295829/f62b083c-bca3-4f89-b8ec-c6368c67ed0a">
**Additional context or questions**

**Comment by Emilgardis** [comment] 2023-11-18 22:21
this is probably #831 

try another name, it's most likely already taken

**Comment by Xemdo** [comment] 2023-11-20 18:18
Duplicate of #831

**Closed by Xemdo** 2023-11-20 18:18 UTC
Labels: product: dev site
