### ISSUE TITLE
Extensions can't be deleted

### ISSUE THREAD

**Issue by davidmaillo** [twitchdev/issues#614] opened 2022-05-23 09:49 UTC
**Brief description**
Extensions can't be deleted after creation from the extension list in dev.twitch.tv/console (Extensions tab)

**How to reproduce**
If you click one of the extensions in the mentioned list, and then go to "Extension Settings > Delete Extension" nothing happens. If you inspect this with browser console, you'll see a GraphQL error.

**Expected behavior**
After clicking Delete Extension it should remove the extension and go back to the Extensions list. Or, in case it doesn't work, it could drop a message with something like "The extension could not be removed".

**How I solved it / Alternative path**
The path I've found to solve it is to create a first VERSION of the extension. Then I enter inside the version 0.0.1, then Extension Settings > Delete Extension and it works.

Hope it helps!

**Comment by BarryCarlyon** [comment] 2022-05-23 11:38
duplicate of #46

**Closed** 2022-07-12 22:30 UTC
Labels: product: dev site
