### ISSUE TITLE
Cannot register twitch app with certain names

### ISSUE THREAD

**Issue by webdeploy-davoli-alessio** [twitchdev/issues#863] opened 2023-11-16 15:53 UTC
**Brief description**
I Cannot register an application which name starts with a number. User should be warned.
**How to reproduce**
Try to register an application with a name that starts with a number
**Expected behavior**
Working application creation wizard or warning about wrong application name.

**Comment by Emilgardis** [comment] 2023-11-16 16:15
The warning not being displayed is known and is tracked in #831

**Comment by Xemdo** [comment] 2023-11-20 18:18
Duplicate of #831

**Closed by Xemdo** 2023-11-20 18:18 UTC
Labels: product: dev site
