### ISSUE TITLE
Can't create a new application

### ISSUE THREAD

**Issue by Lordkaito** [twitchdev/issues#854] opened 2023-10-25 17:59 UTC
**Brief description**
If you try to create a new application from dev.twitch.tv/console it won't allow you to do so
**How to reproduce**
Head to dev.twitch.tv/console
Click on register new app
After introducing the required information for your app and hitting create it will not load and do nothing.
If you check the console using the developer tools for the browser you will see a "Service error"
**Expected behavior**
Should create a new app, load a new page and grant you an ID
**Screenshots**
![Captura de pantalla 2023-10-25 a las 19 58 39](https://github.com/twitchdev/issues/assets/59100477/aaf42261-1738-4175-a8a7-6a23f227abd3)
![Captura de pantalla 2023-10-25 a las 19 58 49](https://github.com/twitchdev/issues/assets/59100477/2ec6d2b9-cc80-447b-8d68-90d1e055e4cb)
**Additional context or questions**

**Comment by iProdigy** [comment] 2023-10-25 18:01
Duplicate of https://github.com/twitchdev/issues/issues/831 - try a unique app name

**Closed** 2023-10-30 22:53 UTC
Labels: product: dev site
