### ISSUE TITLE
Can't register app

### ISSUE THREAD

**Issue by AlexGouget** [twitchdev/issues#882] opened 2023-12-26 00:53 UTC
I can't record new App. I only have console error: 

![image](https://github.com/twitchdev/issues/assets/13834739/21b959ee-f2ce-424f-a19f-c6e9d17cf692)

**Comment by iProdigy** [comment] 2023-12-26 01:38
Duplicate of https://github.com/twitchdev/issues/issues/831

Your app name must be unique and not contain "twitch"

**Comment by Xemdo** [comment] 2023-12-29 23:39
Indeed a duplicate of #831. Closing

**Closed by Xemdo** 2023-12-29 23:39 UTC
Labels: product: authentication
