### ISSUE TITLE
[Helix] Followed Live Streams returning empty user_name field

### ISSUE THREAD

**Issue by S0und** [twitchdev/issues#576] opened 2022-02-19 16:45 UTC
**Brief description**
When a user follows a streamer, and this streamer starts to stream, this fact is published in `https://api.twitch.tv/helix/streams/followed` to the user. The problem is, when the streamer goes live, in the first ~30 seconds the `user_name` (displayName) is not published in `https://api.twitch.tv/helix/streams/followed` result, while EVERY OTHER information is. So only `user_name` is missing, and only missing for the first ~30seconds. 

**How to reproduce**
Have two accounts, follow account A with account B, go live with account A, query `https://api.twitch.tv/helix/streams/followed` with account B. Account A will show up, but without `user_name`, if you query it again a few seconds later, the `user_name` will be there. 

**Expected behavior**
I expect that the `user_name` is always part of the query result **regardless** WHEN i turn the query. Especially when `user_id` and `user_login` is always in the result. 

**Screenshots**
![image](https://user-images.githubusercontent.com/1266308/154809795-508f028e-ad23-4588-a79c-3f1993e7b3fb.png)

**Video**
I went live, on my main account, and i'm querying `https://api.twitch.tv/helix/streams/followed` with my dev account. You can clearly see that the `user_name` is empty for a good 30 seconds. 
https://streamable.com/18sinc

**Additional context or questions**
https://discuss.dev.twitch.tv/t/helix-followed-live-streams-returning-empty-user-name-field/35859

I highly disagree with the mod's response, since it's just wrong. This is not about how often i run the query, but WHEN i run it. I can run it once a week in that 30sec window, and i get a result with empty `user_name`.

**Comment by BarryCarlyon** [comment] 2022-02-19 19:24
Duplicate #500

**Comment by Xemdo** [comment] 2023-08-22 19:41
Closed as duplicate of #500

**Closed by Xemdo** 2023-08-22 19:41 UTC
Labels: product: api
