### ISSUE TITLE
channel.subscription.message triggers for fresh prime subs when it shouldn't

### ISSUE THREAD

**Issue by Gambloide** [twitchdev/issues#811] opened 2023-07-23 20:44 UTC
**Brief description**
Today someone subscribed to my channel for the first time, and they used their amazon Prime sub.
My bot received BOTH a `channel.subscribe` and a `channel.subscription.message` event from the EventSub Websocket interface for this event.

The documentation for `channel.subscription.message`[1] clearly states that it is ONLY for resubscriptions.

**How to reproduce**
Listen to `channel.subscription.message` and have someone who was previously not subscribed subscribe with their Prime sub.

**Expected behavior**
No `channel.subscription.message` event is sent.

**Screenshots**
Subscription info from the Twitch Dashboard:
![image](https://github.com/twitchdev/issues/assets/5939852/84d0da52-346b-4bdb-89b6-50d583dcb6dc)

`channel.subscribe` event:
![image](https://github.com/twitchdev/issues/assets/5939852/53380c73-3727-4fb0-b2bb-523f5bdcff47)

`channel.subscription.message` event:
![image](https://github.com/twitchdev/issues/assets/5939852/9b7652c9-ec40-4035-9d90-94e81f6026a2)

**Additional context or questions**
[1] https://dev.twitch.tv/docs/eventsub/eventsub-subscription-types/#channelsubscriptionmessage

**Comment by igorpo** [comment] 2024-04-22 19:04
The issue is now fixed.

**Closed by igorpo** 2024-04-22 19:04 UTC
Labels: product: eventsub
