### ISSUE TITLE
Can´t Create applecation

### ISSUE THREAD

**Issue by Wutzuket** [twitchdev/issues#848] opened 2023-10-12 12:24 UTC
**Brief description**
I can´t create a applecation. If i pressed "create" nothing happents but i have all filled out
**How to reproduce**
Try to create an applecation an press "create"
**Expected behavior**
An applecation should be created
**Screenshots**
![image](https://github.com/twitchdev/issues/assets/98548330/a1f11c92-e9ff-4b87-8728-2364a440722d)

**Additional context or questions**

**Comment by Wissididom** [comment] 2023-10-12 12:42
Likely duplicate of #831

**Comment by BarryCarlyon** [comment] 2023-10-12 18:19
Also for the record you cannot use `twitch` in the name it's a reserved word.

**Comment by Xemdo** [comment] 2023-10-13 18:08
This is indeed a duplicate of 831. Barry is also correct, the application creation failed due to including a reserved word (_Twitch_) in the name.

**Closed by Xemdo** 2023-10-13 18:08 UTC
Labels: product: dev site
