### ISSUE TITLE
Get Broadcaster Subscriptions endpoint results is missing subscirptions that are present in "Download My Subscriber List" file

### ISSUE THREAD

**Issue by csunday95** [twitchdev/issues#187] opened 2020-08-05 03:44 UTC
**Brief description**
When using the Helix `Get Broadcaster Subscriptions` endpoint, the set of subscriptions obtained differs from the complete list of subscribers available for download from the Channel Analytics page of a broadcaster. This difference follows a strange pattern that all the missing subs are within packs of gifted subs; the larger the pack the more are missing.

**How to reproduce**
 - Use the Helix API `Get Broadcaster Subscriptions` endpoint as normal to obtain a list of all the broadcaster subscriptions
 - concurrently download the list of subscribers from a user's analytics page
 - compare the list of subscribers obtained via Helix to the list downloaded
 - in the test I was running, there were dozens of missing subscriptions with the strange correlation that all were within gifted sub packs of at least 5. The bulk of the missing subs were in a pack of 50. 

**Expected behavior**

The Helix API endpoint for subscribers has a near exact correspondence with the downloaded sub list.

**Comment by brandinarsenault** [comment] 2020-08-05 23:15
Also reported on #184 seems to be a recent active issue - not sure what changed

**Comment by lleadbet** [comment] 2020-09-16 16:53
As noted above, this seems to be a duplicate of the issue of #184 which has since been resolved. 

If you're still missing subscriptions, please reopen this and tag me- thanks!

**Closed by lleadbet** 2020-09-16 16:53 UTC
Labels: product: helix
