### ISSUE TITLE
Helix Videos API does not return game

### ISSUE THREAD

**Issue by BtbN** [twitchdev/issues#58] opened 2020-02-12 20:06 UTC
**Brief description**

The /helix/videos endpoint does not return any info about what game(s) was/were played in that video.

**Expected behavior**

The response JSON should contain at least the first game played in that video, like the old v5 API does. Either as game name, ID, or ideally even both.

**Additional context or questions**

There does not appear to be a way to get that information at all. So currently, one has to fall back to single-video v5 API calls to get that information.

**Comment by BarryCarlyon** [comment] 2020-02-13 15:52
I'd vote for a FULL chapters object.

Pseudo object example

```
{
    vod_id
    channel_id
    stream_start: UNIX
    chapters: [
        {
            started_at: UNIX,
            uptime_into_vod: seconds_since_start_of_vod
            title:
            game_id
        },
        {
            started_at: UNIX,
            uptime_into_vod: seconds_since_start_of_vod
            title:
            game_id
        }
    ]
}
```

**Comment by mauerbac** [comment] 2020-03-23 19:16
thanks @BtbN . Submitted internally -> HLX-1325

**Comment by jimgrimmett** [comment] 2021-01-18 11:16
Are the chapters/game details for VODs going to be in a release soon? This is one of the main things stopping us from leaving Kraken behind (along with some of the old Kraken channel data that isn't on user yet e.g follower count)

**Comment by BarryCarlyon** [comment] 2021-01-18 13:00
> Are the chapters/game details for VODs going to be in a release soon

Chapters (gameID's/offset timestamps) has a uservoice - https://twitch.uservoice.com/forums/310213-developers/suggestions/38155990-return-tags-and-game-id-in-get-videos-in-helix to upvote instead

> Kraken behind (along with some of the old Kraken channel data that isn't on user yet e.g follower count)

For Follower count: call the followers API (with `?first=1` and read the total), for the total, it (probably) won't be "added" to the `user` output.

**Comment by jimgrimmett** [comment] 2021-01-18 16:34
Thanks, I've voted in the uservoice.

Thanks for the note about GetUserFollows I either missed it the total wasn't there last time I looked - lets be honest, I missed it.

Cheers, Jim.

**Comment by Planks** [comment] 2021-07-17 17:51
> thanks @BtbN . Submitted internally -> HLX-1325

I'd like to ask if there is internal progress on this ticket as still no equivalent data in the helix endpoint v5 now has an official EOL.

**Comment by josephschorr** [comment] 2022-01-01 23:45
Just adding onto this: My use of the video API has a *critical* dependency on the ability to determine the game of the video and I'm still stuck on v5 video API as a result.

I'm also blocked by the lack of the broadcast platform information as well. Can we get an issue filed to have the `broadcast_platform` added back into the video information?

**Comment by BarryCarlyon** [comment] 2022-01-02 14:23
> Can we get an issue filed to have the broadcast_platform added back into the video information?

You need a uservoice for this (not a bug report)

https://twitch.uservoice.com/forums/310213-developers

For game on videos (and tags)

https://twitch.uservoice.com/forums/310213-developers/suggestions/38155990-return-tags-and-game-id-in-get-videos-in-helix

But for games+offsets for when a game change happens in a video/stream

https://twitch.uservoice.com/forums/310213-developers/suggestions/42720509-highlight-vod-offset-origin-vod

**Comment by josephschorr** [comment] 2022-01-02 20:03
@BarryCarlyon Much appreciated for the pointers. Will file a uservoice.

**Comment by Xemdo** [comment] 2023-08-11 17:10
Since this is a feature request and not a bug in Get Videos, I'll close this out

**Closed by Xemdo** 2023-08-11 17:10 UTC
Labels: product: api, ticketed

**Comment by Planks** [comment] 2023-08-11 17:29
> Since this is a feature request and not a bug in Get Videos, I'll close this out

What's the status of the internal ticket HLX-1325? It is after all a regression, and one that was reported in good time for v5's deprication, not a feature request.

**Comment by Xemdo** [comment] 2023-08-15 21:41
HLX-1325 was moved into another internal ticket that's tracking the development of the feature request mentioned on https://twitch.uservoice.com/forums/310213/suggestions/38155990

As far as v5/Helix migration currently is seen, misses in feature parity are unfortunately not a bug. Any additional features being added into Helix that replicate the features from v5 are considered a feature request for Helix.
