### ISSUE TITLE
Fails to create an application when there is the app with same name exists

### ISSUE THREAD

**Issue by teruyam** [twitchdev/issues#840] opened 2023-09-18 18:31 UTC
**Brief description**
When I try to create an application at [register application](https://dev.twitch.tv/console/apps/create), press "create" button does nothing.

**How to reproduce**
- Put common name for app name, for example "MyFirstApp".
- Press "create"
- The page does not navigate at all.

**Expected behavior**
As far as I tested, an app name is unique and cannot be duplicated.
Therefore, UI should tell me that the name is already taken.
When backend returns some errors, UI should tell me.

**Screenshots**
None

**Additional context or questions**
Looking at http requests and responses, gql endpoint with "CreateOauthApp" reutrns "service error".

**Comment by iProdigy** [comment] 2023-09-18 18:38
Duplicate of #831

**Comment by Xemdo** [comment] 2023-09-18 20:26
Indeed it is. Closing this out as a duplicate.

**Closed by Xemdo** 2023-09-18 20:26 UTC
Labels: product: dev site
