### ISSUE TITLE
If you click on the link to the "Twitch Developer Setup" download you get a warning.

### ISSUE THREAD

**Issue by LittleKita** [twitchdev/issues#319] opened 2021-02-21 18:08 UTC
**Brief description**
If i try to download "Twitch Developer Setup" there is a Warning:
STOP - there might be a problem with the requested link
The link you requested has been identified by bitly as being potentially problematic.
......

**How to reproduce**
Open the status page of an extension:
https://dev.twitch.tv/console/extensions/..../..../status
Click on "Download developer testing tools" (sorry i only have the German text)
The following link shows a Warning after clicking:
https://link.twitch.tv/DevRig-Win
This redirects to https://bitly.com/a/warning?hash=3fXfrES&url=https%3A%2F%2Fdeveloper-rig.twitchcdn.net%2FTwitch%2BDeveloper%2BRig%2BSetup.exe

**Expected behavior**
Download without warnings.

**Screenshots**
![2021-02-21 19_06_41-Warning! _ There might be a problem with the requested link](https://user-images.githubusercontent.com/6247688/108634053-101a7900-7478-11eb-933d-1dce7aa1c553.png)

**Additional context or questions**

**Comment by BarryCarlyon** [comment] 2021-02-22 14:49
Looks like a false positive from bit.ly

https://dev.twitch.tv/docs/extensions/rig

As some _better_ links.

The dashboard/status page should be updated to use the same links perhaps

**Comment by lleadbet** [comment] 2021-02-22 17:15
This is a duplicate of #156 and is being tracked currently.

**Closed by lleadbet** 2021-02-22 17:15 UTC
Labels: product: dev site
