### ISSUE TITLE
Scope parameter does not work with refresh token

### ISSUE THREAD

**Issue by Natro-Kai** [twitchdev/issues#595] opened 2022-04-26 16:17 UTC
**Brief description**
When trying to contain scopes of a token with the help of the refresh token, one still gets all rights with the returned token that the user has approved.

**How to reproduce**
1) Create a refresh token as shown in the docs with multiple scopes (chat:read, channel:read:goals, channel:read:hype_train).
2) Generate a new token and add the parameter "scope=chat:read".

Also under /validate the token has all scopes

**Expected behavior**
The newly generated token should have only the scopes mentioned in the parameters

**Screenshots**
https://i.imgur.com/6S92Grw.png

**Additional context or questions**
-

**Comment by iProdigy** [comment] 2022-04-26 16:20
Duplicate of #178

**Comment by Xemdo** [comment] 2023-07-27 01:29
Closing in favor of 178

**Closed by Xemdo** 2023-07-27 01:29 UTC
Labels: duplicate, product: authentication
